version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger/api.yaml:/usr/share/nginx/html/api.yaml
      - ./swagger/api_simple.yaml:/usr/share/nginx/html/api_simple.yaml
    environment:
      API_URL: api.yaml
    ports:
      - "8880:8080"

  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8888:8080"
    links:
      - db:db
  
  db:
    build:
      context: ./db
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pouch
      - MYSQL_USER=pouch
      - MYSQL_PASSWORD=secret
    expose:
      - 3306
    ports:
      - 33061:3306
