version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger/api.yaml:/usr/share/nginx/html/api.yaml
    environment:
      API_URL: api.yaml
    ports:
      - "8880:8080"

  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8888:8080"
