openapi: 3.0.0
info:
  description: >-
    Pouch api server.
    [c8112002/pouch-api](https://github.com/c8112002/pouch-api)
  version: 1.0.0
  title: Pouch API Server
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: c8112002@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /v1
tags:
  - name: article
    description: Everything about Articles
  - name: comment
    description: Everything about Comments
  - name: tag
    description: Everything about Tags
schemes:
  - http
  - https
paths:
  /articles:
    get:
      tags:
        - article
      summary: Return articles
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articles'
        '405':
          description: Invalid input
      security:
        - api_key: []
  /article:
    post:
      tags:
        - article
      summary: Post an article.
      parameters:
        - name: url
          in: query
          required: true
          description: Article's url.
          schema:
            type : string
        - name: tags
          in: query
          required: true
          description: Tags related to a article.
          schema:
            type : array
        - name: comment
          in: query
          required: false
          description: Comment related to a article.
          schema:
            type : string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '405':
          description: Invalid input
      security:
        - api_key: []
  /articles/{articleId}:
    get:
      tags:
        - article
      summary: Return an article.
      parameters:
        - name: articleId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '405':
          description: Invalid input
      security:
        - api_key: []
  /articles/{articleId}/comments:
    get:
      tags:
        - comment
      summary: Return an comments.
      parameters:
        - name: articleId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comments'
        '405':
          description: Invalid input
      security:
        - api_key: []
  /tags:
    get:
      tags:
        - tag
      summary: Return tags
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tags'
        '405':
          description: Invalid input
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
components:
  schemas:
    Articles:
      type: array
      items:
        $ref: '#/components/schemas/Article'
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        url:
          type: string
        image_path:
          type: string
    Comments:
      type: array
      items:
        $ref: '#/components/schemas/Comment'
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        body:
          type: string
    Tags:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        count:
          type: integer
          format: int64