openapi: 3.0.0
info:
  description: >-
    Pouch api server.
    [c8112002/pouch-api](https://github.com/c8112002/pouch-api)
  version: 1.0.0
  title: Pouch API Server
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: c8112002@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /v1
tags:
  - name: article
    description: Everything about Articles
  - name: comment
    description: Everything about Comments
  - name: tag
    description: Everything about Tags
schemes:
  - http
  - https
paths:
  /articles:
    get:
      tags:
        - article
      summary: get articles
      description: ''
      operationId: getArticles
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          $ref: '#/components/schemas/Articles'
        '405':
          description: Invalid input
      security:
        - api_key: []
  /article/{articleId}:
    get:
      tags:
        - article
      summary: get article
      description: ''
      operationId: getArticle
      parameters:
      - in: path
        name: articleId
        type: integer
        required: true
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          $ref: '#/components/schemas/Article'
        '405':
          description: Invalid input
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
components:
  schemas:
    Articles:
      type: array
      items:
        $ref: '#/components/schemas/Article'
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        url:
          type: string
        image_path:
          type: string
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        body:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string