version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./api.yaml:/usr/share/nginx/html/api.yaml
    environment:
      API_URL: api.yaml
    ports:
      - "8080:8080"
